# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.IntegerField()),
                ('sleep', models.FloatField()),
                ('art', models.IntegerField()),
                ('meditation', models.BooleanField()),
                ('meditation_time', models.FloatField()),
                ('mood', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('shirt_size', models.CharField(choices=[('C', 'Cardio'), ('S', 'Strength'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='myblog',
            name='tags',
        ),
        migrations.DeleteModel(
            name='MyBlog',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='entry',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Exercise'),
        ),
    ]
