# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20170630_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='shirt_size',
            new_name='exercise_type',
        ),
    ]
