# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20170630_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.Exercise'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='meditation_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='miles',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
