# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-01 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20170630_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mood_number',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('C', 'Cardio'), ('S', 'Strength'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
