# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_entry_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angry', models.FloatField()),
                ('happy', models.FloatField()),
                ('calm', models.FloatField()),
                ('sad', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myblog.SScore'),
            preserve_default=False,
        ),
    ]
